config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'panel#map'
  resources :pois, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def human_enum_name(enum_name, enum_value)
    I18n.t("activerecord.enums.#{model_name.i18n_key}.#{enum_name}.#{enum_value}")
  end

  def enum_collection_for_select(enum_name, ignore: [])
    ignore = ignore.class == Array ? ignore : [ignore]
    ignore.map!(&:to_s)
    self.send(enum_name.to_s.pluralize).map do |enum_key, enum_value|
      next if ignore.include?(enum_key)
      [human_enum_name(enum_name, enum_key), enum_key]
    end.compact
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :pois

  validates :name, presence: true

  enum status: { enabled: 1, disabled: 2, deleted: 3}
end

app/models/poi.rb
class Poi < ApplicationRecord
  belongs_to :category, class_name: "Category", foreign_key: "category_id"
  belongs_to :user, class_name: "User", foreign_key: "user_id"

  validates :title, presence: true
  validates :description, presence: true

  enum status: { enabled: 1, disabled: 2, deleted: 3}
end

app/models/user.rb
class User < ApplicationRecord
  has_many :pois
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  layout :layout_by_resource

  private
    def layout_by_resource
      devise_controller? ? "devise" : "application"
    end
end

app/controllers/panel_controller.rb
class PanelController < ApplicationController
  skip_before_action :authenticate_user!

  def map
  end

end

app/controllers/pois_controller.rb
class PoisController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  def index
    @pois = Poi.all

    render json: { pois: @pois }
  end

  def new
    @poi = Poi.new(color: "#3388ff", icon: "taxi")
    render partial: "pois/form"
  end

  def create
    @poi = Poi.new(poi_params.merge(user: current_user))
    if @poi.save
      render json: { response: { message: "El punto de Interés fue creado con éxito." }, status: :ok }
    else
      render partial: "pois/form", status: :unprocessable_entity
    end
  end

  private

    def poi_params
      params.require(:poi).permit(:title, :description, :score, :latitude, :longitude, :icon, :color, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="description" content="App Puntos de interés" />
    <meta name="author" content="Marco De la cruz" />
    <meta name="theme-color" content="#2a3042" />
    <meta property="og:title" content="Marco De la cruz" />
    <meta property="og:description" content="App web donde se puede visualizar los lugares favoritos de los usuarios." />
    <meta property="og:type" content="website">
    <title>Puntos de Interés</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "https://unpkg.com/leaflet@1.8.0/dist/leaflet.css", "integrity": "sha512-hoalWLoI8r4UszCkZ5kL8vayOGVae1oxXe/2A4AO6J9+580uKHDO3JdHb7NzwwzK5xr/Fs0W40kiNHxM9vyTtQ==", "crossorigin": "", "data-turbolinks-track": "reload" %>
    <%= stylesheet_link_tag "https://unpkg.com/@geoman-io/leaflet-geoman-free@latest/dist/leaflet-geoman.css", "data-turbolinks-track": "reload" %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag "https://unpkg.com/leaflet@1.8.0/dist/leaflet.js", "integrity": "sha512-BB3hKbKWOc9Ez/TAwyWxNXeoV9c1v6FIeYiBieIWkpLjauysF18NzgR1MBNBXf8/KABdlkX68nAhlwcDFLGPCQ==", "crossorigin": "", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "https://unpkg.com/@geoman-io/leaflet-geoman-free@latest/dist/leaflet-geoman.min.js", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%#= render "layouts/application/navigation" %>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/layouts/application/_navigation.html.erb
<div id="navegacion">
  <div class="menu">
    <ul>
      <li class="active">
        <a href="#inicio">
          <i class="bi bi-house"></i>
          <span>Inicio</span>
        </a>
      </li>
      <li>
        <a href="#sobremi">
          <i class="bi bi-person"></i>
          <span>Sobre mí</span>
        </a>
      </li>
      <li>
        <a href="#portafolio">
          <i class="bi bi-journal-code"></i>
          <span>Proyectos</span>
        </a>
      </li>
      <% if current_user %>
        <li class="lista">
          <%= link_to destroy_user_session_path, class: "text-danger", data: { method: :delete } do %>
            <i class="fas fa-power-off text-danger"></i>
            Cerrar Sesión
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>

  <button type="button" class="mobile-nav-toggle">
    <i class="fa fa-bars"></i>
  </button>
</div>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Iniciar Sesión</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "login", "data-turbo-track": "reload" %>
  </head>

  <body>
    <main class="login-card">
      <%= render "shared/flash_message" %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/panel/map.html.erb
<div id="panel"
    data-controller="panel popups pois"
    data-pois-url="<%= pois_path %>"
    data-marker-location-icon-url="<%= asset_path('icons/marker-location.png') %>"
>
  <div class="map" data-panel-target="map"></div>

  <div class="panel-top-right-options">
    <% unless current_user %>
      <%= link_to user_session_path, class: "btn btn-primary rounded-circle", title: "Iniciar sesión" do %>
        <i class="fas fa-user"></i>
      <% end %>
    <% else %>
      <%= link_to destroy_user_session_path, class: "btn btn-danger rounded-circle", data: { method: :delete } do %>
        <i class="fa fa-power-off"></i>
      <% end %>

      <%= link_to new_poi_path, id: "new-poi",
            class: "btn btn-secondary rounded-circle ml-2",
            remote: true,
            title: "Registrar punto de interés",
            data: {
              closest_target: ".panel-top-right-options",
              popup_title: "Registrar Punto de Interés",
              controller_target: "Pois",
              action: "
                click->popups#showModule
                click->popups#hidePanelOptions
                ajax:beforeSend->popups#loadingPopupMain
                ajax:success->popups#showContentPopupMain
                ajax:success->pois#showPoiForm
              "
            } do %>
        <i class="fas fa-plus"></i>
      <% end %>
    <% end %>
  </div>

  <div class="panel-bottom-right-options">
    <button type="button" class="panel-options-icon" title="Mostrar ubicación actual" data-action="panel#getLocation panel#focusLastPositionMarker" data-marker-focus="true">
      <%= image_tag("icons/current-location.svg", size: 40) %>
    </button>
  </div>

  <div class="panel-popup" data-popups-target="panelPopup"></div>
</div>

app/views/pois/_form.html.erb
<div>
  <div class="popup-header">
    <h6 class="font-weight-bold mb-0">Registrar Punto de Interés</h6>
    <button type="button" class="btn btn-secondary btn-sm rounded-circle btn-close ml-auto"
      data-action="
        click->popups#showPanelOptions
        click->popups#closePopup
        click->pois#cancelPoiForm
      "
      data-link-target="#new-poi">
      <i class="fa fa-times"></i>
    </button>
  </div>
  <div class="popup-main p-3">
    <%= form_with(model: @poi, remote: true, id: "poi-form", data: {
      poi: @poi.to_json,
      action: "
        ajax:success->pois#successPoiForm
        ajax:success->popups#showPanelOptions
        ajax:success->popups#closePopup
        ajax:error->popups#showContentPopupMain
      ",
      link_target: @poi.new_record? ? "#new-poi" : ""
    }) do |form| %>
      <%= render "shared/errors", obj: @poi %>
      <div class="row">
        <div class="form-group col-12 mb-3">
          <%= form.label :title %>
          <%= form.text_field :title, class: "form-control form-control-sm", required: true %>
        </div>
        <div class="form-group col-12 mb-3">
          <%= form.label :description %>
          <%= form.text_field :description, class: "form-control form-control-sm ", required: true %>
        </div>
        <div class="form-group col-6 mb-3">
          <%= form.label :color %>
          <%= form.text_field :color, class: "form-control form-control-sm color-picker-input", required: true %>
        </div>
        <div class="form-group col-6 mb-3">
          <%= form.label :score %>
          <%= form.text_field :score, class: "form-control form-control-sm ", required: true %>
        </div>
        <div class="form-group col-12 mb-3">
          <%= form.label :category_id %>
          <%= form.collection_select :category_id, Category.all, :id, :name, { prompt: "Seleccionar" }, { class: "form-control form-control-sm" } %>
        </div>
        <div class="form-group col-6 mb-3">
          <%= form.label :latitude %>
          <%= form.text_field :latitude, class: "form-control form-control-sm ", required: true, readonly: true %>
        </div>
        <div class="form-group col-6 mb-3">
          <%= form.label :longitude %>
          <%= form.text_field :longitude, class: "form-control form-control-sm ", required: true, readonly: true %>
        </div>
        <div class="form-group col-6 mb-3">
          <%= form.submit class: "btn btn-primary btn-sm" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h6 class="font-weight-bold "><%= I18n.t("errors.template.header", count: obj.errors.count, model: obj.class.model_name.human) %></h6>
    <ul class="px-3">
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% if flash[:notice] %>
  <div class="flash_notice alert alert-success" >
    <span><%= notice %></span>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="flash_alert alert alert-danger" >
    <span><%= alert %></span>
  </div>
<% end %>